title = "Kunal Sharda"
baseurl = "https://ksharda.me"
languagecode = "en"
defaultcontentlanguage = "en"
theme = "hugo-coder"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "ksharda"

[params]
hideCopyright = false
dateformat = "January 2, 2006"
colorscheme = "light"
maxSeeAlsoItems = 5
rtl = false
keywords = "blog,developer,personal,entrepreneur,life"
author = "Kunal Sharda"
info = "Student Builder, Maker, and Realist"
custom_css = []
avatarurl = "images/avatar.jpg"
custom_js = []
commit = "https://github.com/rektipieces/hugo-coder/"
hideCredits = false
since = 2019
description = "Kunal Sharda's personal website"
hideFooter = false
footercontent = ""

[[params.social]]
name = "Github"
icon = "fab fa-github"
weight = 1
url = "https://github.com/rektinpieces/"

[[params.social]]
name = "Gitlab"
icon = "fab fa-gitlab"
weight = 2
url = "https://gitlab.scintillating.us"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/kunal-sharda/"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
weight = 6
url = "https://ksharda.me/index.xml"
rel = "alternate"
type = "application/rss+xml"

[params.fathomAnalytics]
siteID = "ABCDE"
serverURL = "analytics.example.com"

[languages]

[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3

[[languages.en.menu.main]]
name = "Résumé + Contact"
url = "https://www.linkedin.com/in/kunal-sharda/"
weight = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"